name: Tareas

on:
  schedule:
    - cron: '0 7 * * 1'
  workflow_dispatch:

jobs:
  tareas:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: cd scripts && python resumen_tareas_lunes.py
